### ISSUE TITLE
receptek kezelése

### ISSUE THREAD

**Issue by BendeHuba** [Szemethy/Nagymama-recept-Tuti-recept#5]
Receptek kezelése - Alapvetően minden adatot az etelek.csv fájlból nyer ki és azok segítségével dolgozik. Előszőr is van egy menu fájl ami a menü programját tartalmazza. Ezek után van egy functions fájl amiben  a különböző feladatok, funkciók programja van, mint pl. Keresés név alapján vagy étel módosítása és van a receptek fájl ami az előző két fájlt egyesíti, hogy működőképes legyen.

**Comment by tomposgergo2** [comment]
Új étel rögzítése és eltárolása a csv fájlban kész.
